# Configurações do Banco de Dados
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/atletahub}
spring.datasource.username=${DB_USERNAME:atletahub_user}
spring.datasource.password=${DB_PASSWORD:desantamaroavdn2018}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.main.allow-circular-references=true

# Configurações JWT
jwt.secret-key=b1hzi01HyTCEixi9seAczIyUe75VsuadzwbV5OJb548=
jwt.expiration-time=86400000
  # 1 dia em milissegundos (24 * 60 * 60 * 1000)


