# Configura��es do Banco de Dados para DEPLOY NO RAILWAY
# Use as vari�veis conforme elas aparecem no seu servi�o de backend no Railway (atletahub-api)
spring.datasource.url=${MYSQL_URL} # Esta � a que o Railway injeta como a URL interna completa
spring.datasource.username=${MYSQLUSER} # Conforme suas vari�veis no Railway (sem underscore)
spring.datasource.password=${MYSQLPASSWORD} # Conforme suas vari�veis no Railway (sem underscore)

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.main.allow-circular-references=true

# Configura��es JWT - usando as vari�veis que voc� j� tem no servico de backend
jwt.secret-key=${jwt.secret-key}
jwt.expiration-time=${jwt.expiration-time}