# Configurações do Banco de Dados
spring.datasource.url=${DB_URL:jdbc:root:dAlDhOYiFjhRJEDGqaVfbktJVLPoGLkp@mysql.railway.internal:3306/railway}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:dAlDhOYiFjhRJEDGqaVfbktJVLPoGLkp}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.main.allow-circular-references=true

# Configurações JWT
jwt.secret-key=b1hzi01HyTCEixi9seAczIyUe75VsuadzwbV5OJb548=
jwt.expiration-time=86400000
  # 1 dia em milissegundos (24 * 60 * 60 * 1000)


